version: '3'
services:
  rs0-node1:
    container_name: rs0-node1
    image: mongo:4.2.6-bionic
    command: mongod --config /etc/mongo/mongod.conf
    expose:
      - "27017"
    volumes:
      - ./rs0/node1.conf:/etc/mongo/mongod.conf
      - ./data/rs0-node1:/data/db
  rs0-node2:
    container_name: rs0-node2
    image: mongo:4.2.6-bionic
    command: mongod --config /etc/mongo/mongod.conf
    expose:
      - "27017"
    volumes:
      - ./rs0/node2.conf:/etc/mongo/mongod.conf
      - ./data/rs0-node2:/data/db
  rs0-node3:
    container_name: rs0-node3
    image: mongo:4.2.6-bionic
    command: mongod --config /etc/mongo/mongod.conf
    expose:
      - "27017"
    volumes:
      - ./rs0/node3.conf:/etc/mongo/mongod.conf
      - ./data/rs0-node3:/data/db
